# Generated by Django 4.1.1 on 2022-09-26 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("write", models.TextField()),
                ("memo", models.TextField()),
                (
                    "post_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
