# Generated by Django 4.1.1 on 2022-09-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="memo", old_name="write", new_name="writer",),
    ]
