# Generated by Django 4.1.1 on 2022-09-27 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gusstbook",
            name="post_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
